imports:
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_database.yaml }
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    CodelyTv\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: ['codely.domain_event_subscriber']

  CodelyTv\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  CodelyTv\Apps\Mooc\Backend\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  # Wire
  CodelyTv\:
    resource: '../../../../src'

  # -- TAGGING --
  CodelyTv\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [!tagged codely.domain_event_subscriber]
    lazy: true

  CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [!tagged codely.domain_event_subscriber]

  CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [!tagged codely.domain_event_subscriber]

  CodelyTv\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [!tagged codely.database_connection]

  CodelyTv\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


  # -- APP DEFINITIONS --
  # RabbitMQ
  CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMQConnection:
    arguments:
      - host: '%env(RABBITMQ_HOST)%'
        port: '%env(RABBITMQ_PORT)%'
        vhost: '%env(RABBITMQ_VHOST)%'
        login: '%env(RABBITMQ_LOGIN)%'
        password: '%env(RABBITMQ_PASSWORD)%'
        read_timeout: 0.2
        write_timeout: 0.2
        connect_timeout: 0.2

  CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus:
    arguments: ['@CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMQConnection', '%env(RABBITMQ_EXCHANGE)%']


  # -- IMPLEMENTATIONS SELECTOR --
  CodelyTv\Shared\Domain\Bus\Event\EventBus: '@CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus'
